apiVersion: apps/v1
kind: Deployment
metadata:
  name: puyuan7toazure
  labels:
    app: puyuan7toazure
  namespace: namespace-workflow-1685943827349
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puyuan7toazure
  template:
    metadata:
      labels:
        app: puyuan7toazure
    spec:
      containers:
        - name: puyuan7toazure
          image: acrworkflow1685943827349.azurecr.io/image-workflow-1685943827349:latest
          ports:
            - containerPort: 7202