apiVersion: apps/v1
kind: Deployment
metadata:
  name: puyuantoazure0609
  labels:
    app: puyuantoazure0609
  namespace: namespace-workflow-1686297650444
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puyuantoazure0609
  template:
    metadata:
      labels:
        app: puyuantoazure0609
    spec:
      containers:
        - name: puyuantoazure0609
          image: acrworkflow1686297650444.azurecr.io/image-workflow-1686297650444:latest
          ports:
            - containerPort: 5000