apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-autopush
  labels:
    app: aks-autopush
  namespace: namespace-workflow-1686544689833
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-autopush
  template:
    metadata:
      labels:
        app: aks-autopush
    spec:
      containers:
        - name: aks-autopush
          image: acrworkflow1686544689833.azurecr.io/image-workflow-1686544689833:latest
          ports:
            - containerPort: 7202