apiVersion: apps/v1
kind: Deployment
metadata:
  name: puyuantoazure-2-0609
  labels:
    app: puyuantoazure-2-0609
  namespace: namespace-workflow-1686302024505
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puyuantoazure-2-0609
  template:
    metadata:
      labels:
        app: puyuantoazure-2-0609
    spec:
      containers:
        - name: puyuantoazure-2-0609
          image: acrworkflow1686302024505.azurecr.io/image-workflow-1686302024505:latest
          ports:
            - containerPort: 5202