apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-auto-push
  labels:
    app: aks-auto-push
  namespace: namespace-workflow-1686541660695
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-auto-push
  template:
    metadata:
      labels:
        app: aks-auto-push
    spec:
      containers:
        - name: aks-auto-push
          image: acrworkflow1686541660695.azurecr.io/image-workflow-1686541660695:latest
          ports:
            - containerPort: 7202