apiVersion: v1
kind: Service
metadata:
  name: puyuantoazure
  namespace: namespace-workflow-1685943490831
spec:
  type: LoadBalancer
  selector:
    app: puyuantoazure
  ports:
    - protocol: TCP
      port: 7202
      targetPort: 7202