apiVersion: v1
kind: Service
metadata:
  name: aks-autopush
  namespace: namespace-workflow-1686544689833
spec:
  type: LoadBalancer
  selector:
    app: aks-autopush
  ports:
    - protocol: TCP
      port: 7202
      targetPort: 7202