apiVersion: v1
kind: Service
metadata:
  name: aks-auto-push
  namespace: namespace-workflow-1686541660695
spec:
  type: LoadBalancer
  selector:
    app: aks-auto-push
  ports:
    - protocol: TCP
      port: 7202
      targetPort: 7202