apiVersion: v1
kind: Service
metadata:
  name: puyuan7toazure
  namespace: namespace-workflow-1685943827349
spec:
  type: LoadBalancer
  selector:
    app: puyuan7toazure
  ports:
    - protocol: TCP
      port: 7202
      targetPort: 7202