apiVersion: v1
kind: Service
metadata:
  name: puyuantoazure0609
  namespace: namespace-workflow-1686297650444
spec:
  type: LoadBalancer
  selector:
    app: puyuantoazure0609
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000