apiVersion: v1
kind: Service
metadata:
  name: puyuantoazure-2-0609
  namespace: namespace-workflow-1686302024505
spec:
  type: LoadBalancer
  selector:
    app: puyuantoazure-2-0609
  ports:
    - protocol: TCP
      port: 5202
      targetPort: 5202