apiVersion: v1
kind: Service
metadata:
  name: puyuan7demo0605
  namespace: namespace-workflow-1685945829635
spec:
  type: LoadBalancer
  selector:
    app: puyuan7demo0605
  ports:
    - protocol: TCP
      port: 5202
      targetPort: 5202